#!/bin/bash
# Author: Katie Bickerton k.bickerton@imperial.ac.uk
# Script: miniproject.sh
# Desc: Runs miniproject data collection, analysis, model fitting, and
# generates LATEX report
# Arguments: none
# Date: 28 Feb 2019

# data_wrangling.py manipulated data into a suitable format for modelling in R
# saved to a csv file in the Data directory.
echo "Welcome to my miniproject!"
echo "Data wrangling is about to start using python, this may take several 
minutes so feel free to get a coffee whilst you wait!"

python3 data_wrangling.py

echo "Data has been successfully saved into an appropriate format for model 
building and fitting in R."

# model_fitting.R reads in the dataframe from python, builds models and fits data
# to the models using non-linear least squares, then uses Akaike Information Criterion
# for model selection. Models are plotted and saved to csv for the report.
echo "Time to build, fit and select an appropriate model in R."

Rscript model_fitting.R

echo "Model selection complete."

# compile_PDF.sh compiles a pdf file from miniproject.tex and miniproject.bib, and 
# includes the outputs and plots generated by the model fitting.

bash compile_PDF.sh


